# Generated by Django 5.2.17 on 2026-09-04 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.PositiveIntegerField(verbose_name='Количество врачей')),
                ('arrival_rate', models.FloatField(verbose_name='Поток пациентов, чел/мин')),
                ('service_mean', models.FloatField(verbose_name='Среднее время приёма, мин')),
                ('horizon_min', models.PositiveIntegerField(default=480, verbose_name='Горизонт смены, мин')),
                ('strategy', models.CharField(choices=[('fifo', 'FIFO'), ('priority', 'Приоритетная'), ('dynamic', 'Динамическая')], default='fifo', max_length=16, verbose_name='Стратегия')),
                ('n_runs', models.PositiveIntegerField(default=10, verbose_name='Число прогонов')),
                ('seed', models.IntegerField(blank=True, null=True, verbose_name='Зерно ГПСЧ')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Считается'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка расчёта')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Время расчёта, с')),
            ],
            options={
                'verbose_name': 'Прогон симуляции',
                'verbose_name_plural': 'Прогоны симуляции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_wait_time', models.FloatField(blank=True, null=True, verbose_name='Среднее ожидание, мин')),
                ('max_wait_time', models.FloatField(blank=True, null=True, verbose_name='Макс. ожидание, мин')),
                ('avg_queue_length', models.FloatField(blank=True, null=True, verbose_name='Средняя очередь, чел')),
                ('doctor_utilization', models.FloatField(blank=True, null=True, verbose_name='Загрузка врачей')),
                ('patients_served', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обслужено пациентов')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='web.simulationrun')),
            ],
            options={
                'verbose_name': 'Результат симуляции',
                'verbose_name_plural': 'Результаты симуляции',
            },
        ),
    ]
