# Generated by Django 5.2.17 on 2026-09-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Симуляция больницы', max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.IntegerField(verbose_name='Номер пациента')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('arrival_time', models.FloatField(verbose_name='Время прихода')),
                ('start_service_time', models.FloatField(blank=True, null=True, verbose_name='Начало приема')),
                ('wait_time', models.FloatField(blank=True, null=True, verbose_name='Время ожидания')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='web.task')),
            ],
        ),
    ]
