# Generated by Django 5.2.17 on 2026-09-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_task_name_patientlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientLog',
        ),
    ]
